name: n2venv
channels:
  - conda-forge
  - psi4
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - scipy
  - psi4
  - matplotlib
  - pylibxc  
  - nbconvert
    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Pip-only installs
  - pip:
    - opt-einsum
    - ntov